### ISSUE TITLE
String: 'http://user:pass@host.com host.com' causes exception

### ISSUE THREAD

**Issue by ddosoff** [linkedin/URL-Detector#12]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:908)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:854)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at com.linkedin.urls.detection.UrlDetector.readDefault(UrlDetector.java:191)
	at com.linkedin.urls.detection.UrlDetector.detect(UrlDetector.java:142)
	at com.mycompany.url.UrlTest.main(UrlTest.java:26)

**Comment by pgalbraith** [comment]
Until this repo is published again, I have this fix included in a separate published build as io.github.pgalbraith:url-detector:0.1.18

https://github.com/pgalbraith/URL-Detector/releases/tag/url-detector-0.1.18
